### PR TITLE
u3: fix snapshot corruption by preemptively dirtying the loom

### LINKED ISSUE #5565: loom corruption on next/vere
**Describe the bug**
Piers created on `next/vere` as of e4616828c1b07274ec1508dc3177814921040343 encounter loom corruption after significant use.

**To Reproduce**
Steps to reproduce the behaviour:
1. `nix-build -A urbit`
2. `[…]/urbit -F zod -B bin/solid.pill`
3. Exit process with `C-d`, then restart vere
4. `|mount %`
5. Exit process with `C-d`
6. `[…]/urbit zod`, which fails with: `Assertion '!"loom: corrupt"' failed in noun/allocate.c:144`

**System (please supply the following information, if relevant):**
 - OS: noticed on macOS (M1 arch)

**Notify maintainers**
@joemfb @mcevoypeter 

EDITED: fixed repro instructions

### PR DESCRIPTION
**Pull request by joemfb**
fixes #5565, which was introduced in #5477 (the optimizations introduce there depend on all pages being initially dirty).

### CODE REVIEW

**Review by mcevoypeter — APPROVED** [review]
LGTM. I took this as an opportunity to document the high level flow of the snapshotting system and the consequences of the page tracking modifications that we've made.

File: pkg/urbit/noun/events.c [hunk 1]
```diff
@@ -1,6 +1,62 @@
-/* g/e.c
-**
-*/
+//! @file events.c
```
Comment (mrdomino) [inline pkg/urbit/noun/events.c:1]: doxygen? ok if so, but i of course am partial to piping stuff through `par 65`.

**Comment by joemfb** [comment]
I restructured and extended your doc comment, PTAL.

**Comment by mrdomino** [comment]
PR #5579 opened against this branch.

**Review by mcevoypeter — APPROVED** [review]
LGTM. Thanks for polishing the block comment.
