### PR TITLE
King multitenant fixups

### LINKED ISSUE #3187: king haskell kills ships when shutting down multiple ships
**Describe the bug**
If haskell king is running multiple ships in daemon mode and you SIGTERM the king it seems to have to kill the ships rather than close them normally, so next time you start them they have to replay events.
 
**To Reproduce**
Steps to reproduce the behaviour:
1. urbit-king run -d -p \<port\> \<pier1\> \<pier2\>
2. killall urbit-king
3. examine urbit king output then restart ships and observe they replay events

**Expected behaviour**
The ships should shut down normally rather than be killed

**Screenshots**

With one pier (note the serf goes down when asked):
```
KING IS GOING DOWN
piers/lagtuc-socleg-tinnus-napbus shutdown requested
Asking serf to shut down
Serf went down when asked.
Releasing lock file: piers/lagtuc-socleg-tinnus-napbus/.vere.lock
piers/lagtuc-socleg-tinnus-napbus terminated.
```
With two piers:
```
KING IS GOING DOWN
piers/tamrul-middex-tinnus-napbus shutdown requested
piers/lagtuc-socleg-tinnus-napbus shutdown requested
<- //ames %hear
  -> //newt/0v1o4d %send
"KILLING: processWork"
"KILLING: processWork"
Asking serf to shut down
Releasing lock file: piers/lagtuc-socleg-tinnus-napbus/.vere.lock
Ship terminated: piers/lagtuc-socleg-tinnus-napbus
Asking serf to shut down
Releasing lock file: piers/tamrul-middex-tinnus-napbus/.vere.lock
```

**System (please supply the following information, if relevant):**
 - OS: linux64 (arch)
 - 0.10.8
 - jp5fi

### PR DESCRIPTION
**Pull request by eglaysher**
Two fixes: one to make --serf apply to all multitenant piers started, and the other one line needle that I was able to track down: when the king gets a request to shutdown in multitenant mode, it doesn't rebroadcast that request to its serfs.

(This pull request will be easier to review on a per-commit basis.)

Fixes #3187

### CODE REVIEW

File: pkg/hs/urbit-king/lib/Urbit/King/Main.hs [hunk 1]
```diff
@@ -727,6 +727,7 @@ runShipRestarting serfExe r o = do
       loop
     Right () -> do
       logTrace $ display (pier <> " shutdown requested")
+      atomically $ putTMVar vKillPier ()
```
Comment (pilfer-pandex) [inline pkg/hs/urbit-king/lib/Urbit/King/Main.hs:730]: um, wow.

**Review by pilfer-pandex — APPROVED** [review]
