### PR TITLE
king: eyre: add missing printouts with ports

### LINKED ISSUE #3175: urbit-king doesn't print the http port in the dojo on boot
**Describe the bug**
urbit-king doesn't print its http ports in the dojo when it boots, unlike the c king which says:
http: web interface live on http://localhost:8081
http: loopback live on http://localhost:12321
(or whatever)

**To Reproduce**
Steps to reproduce the behaviour:
1. spin up pier with urbit-king
2. look at what it spits out in the terminal

**Expected behaviour**
It should behave like the c king

**Screenshots**
```
> urbit-king run -p 42067 piers/lagtuc-socleg-tinnus-napbus
loom: mapped 2048MB
boot: protected loom
live: loaded: MB/469.991.424
boot: installed 268 jets
~lagtuc-socleg-tinnus-napbus:dojo> 
```

**System (please supply the following information, if relevant):**
 - OS: linux64
 - 0.10.8 (urbit-king)
 - jp5fi

### PR DESCRIPTION
**Pull request by pilfer-pandex**
fixes #3175

### CODE REVIEW

File: pkg/hs/urbit-king/lib/Urbit/Vere/Eyre.hs [hunk 1]
```diff
@@ -270,6 +271,10 @@ startServ multi who isFake conf plan = do
       fil = pierPath <> "/.http.ports"
 
   logDebug $ displayShow ("EYRE", "All Servers Started.", srvId, por, fil)
+  for secPor $ \p ->
+    stderr ("http: secure web interface live on https://localhost:" <> tshow p)
```
Comment (eglaysher) [inline pkg/hs/urbit-king/lib/Urbit/Vere/Eyre.hs:275]: You probably don't want to mention "localhost" in these. Vere doesn't and most of the time, a user won't be accessing it via 127.0.0.1. In the case of the secure web interface, it's wrong since the SSL certificate is extremely unlikely to match "localhost".

Comment (joemfb) [reply pkg/hs/urbit-king/lib/Urbit/Vere/Eyre.hs:275]: I don't love these messages, but it looks to me like they match #3092

Comment (eglaysher) [reply pkg/hs/urbit-king/lib/Urbit/Vere/Eyre.hs:275]: Ah, it looks like I was looking at an out-dated master locally. Up to you ~pilfer if you want to make this change.

Comment (pilfer-pandex) [reply pkg/hs/urbit-king/lib/Urbit/Vere/Eyre.hs:275]: Joe's right that I just copied verbatim the behavior of C here (except for adding the word "secure" in the https case), including the fact that the text "localhost" is hardcoded. I agree that it's a bit weird.

I'm happy to do whatever you guys want here; just let me know what it is.

Comment (Fang-) [reply pkg/hs/urbit-king/lib/Urbit/Vere/Eyre.hs:275]: If it is, somehow, easy to know what IP/domain we're available on, do put that in there.

The reason I put "localhost" in #3092 is because I just wanted to fix the complaints from https://github.com/urbit/urbit/issues/1332#issuecomment-513029707, and figuring those things out was much more involved than I cared for. If you're not running locally, you're likely to understand the implications of "localhost" here.

**Comment by pilfer-pandex** [comment]
How would the king even know that it's at ship.urbit.org? For this, it'd
have to know 1) what ip address it is at and 2) what domain name(s) point
to that ip. And what if there's some complex http proxying scheme going on,
like there usually is? "What domain I represent," IIRC, is generally
implemented as a *piece of configuration* that is input to the program by
the complex proxying environment that runs it, if the program needs to
know, right? Also, if billy is running his ship on our hosting system, does
he even have access to the cli and these printouts?

**Comment by Fang-** [comment]
It was more of a rhetorical suggestion I guess, for all the reasons you described. I think Eyre keeps around some config state wrt this, but in practice "It's Hard" and we can't "Really Know" unless we're explicitly told.

Of course at that point, and indeed in the hosting environment too, what message gets printed here doesn't really matter.

(Didn't mean to hold this up, it's fine to go in afaic!)

**Comment by joemfb** [comment]
Note that your urbit already needs to be told this in order to request a TLS certificate from LetsEncrypt. And king-haskell needs to be told this when running multiple ships in a single process with a shared http server (in order to route requests appropriately). It's not at all out of the question for this information to be available, but the requirements would need to be nailed down and the interfaces/data-flow would need to be designed.

**Comment by pilfer-pandex** [comment]
Seems like we have consensus that this is fine for now, so I'll merge. Thanks guys.
