### PR TITLE
u3: rewrites %ud parser

### LINKED ISSUE #4767: (slav %ud @t) is too lenient when parsing
Allows the first chunk to have 4 digits in a row without a separator. 4 digits in any other chunk is rejected. 

Allows redundant separators.

```
:: 4 in first chunk is okay
(slav %ud '1234')   -> 1.234   
(slav %ud '12345')  -> crash
(slav %ud '1234.5') -> 12.345
(slav %ud '1.234.5678')   -> crash

:: redundant separators are okay
(slav %ud '1234.567.8')   -> 12.345.678
(slav %ud '1234.56..78.') -> 12.345.678
```

### PR DESCRIPTION
**Pull request by joemfb**
Fixes #4767, and improves performance.

There was a jet mismatch in `+slaw`; the `@ud` parser mistakenly allowed leading zeros, and less-than-3-digit blocks between `.` separators. Those bugs have been corrected in a new implementation.

To test the performance, I parsed a big `@ud` in a loop.

```
> =do |*([max=@ud arg=* fun=gate] =|(i=@ud |-(?:(=(max i) ~ =+((fun arg) $(i +(i)))))))
> |start %time
```

The raw parser combinator:

```
> :time (do 1.000 (rap 3 ['123.456.789' (reap 200 '.123.456.789')]) |=(a=@t (rush a dem:ag)))
[%took ~s21..438a]
```

The old, overly-lenient jet:

```
> :time (do 1.000 (rap 3 ['123.456.789' (reap 200 '.123.456.789')]) |=(a=@t (slaw %ud a)))
[%took ~s5..697e]
```

The new jet:

```
> :time (do 1.000 (rap 3 ['123.456.789' (reap 200 '.123.456.789')]) |=(a=@t (slaw %ud a)))
[%took ~s0..226a]
> :time (do 10.000 (rap 3 ['123.456.789' (reap 200 '.123.456.789')]) |=(a=@t (slaw %ud a)))
[%took ~s0..769a]
> :time (do 100.000 (rap 3 ['123.456.789' (reap 200 '.123.456.789')]) |=(a=@t (slaw %ud a)))
[%took ~s3..dd65]
```

### CODE REVIEW

**Comment by tacryt-socryp** [comment]
God bless

**Comment by ohAitch** [comment]
Sanity check, how often are we parsing indirect `@ud`? The comparison for like `'12.345'` will probably be more relevant(and further favor the C parser), and unless the answer is "often" it seems wise to rip out all bigint handling and defer to the hoon implementation for input strings length >11(making the C logic even faster)

**Comment by ohAitch** [comment]
("or input strengths of length 12 that start with '1' or '2.0'" if you want to cover almost all 0..2^31, but if we're not seeing @ud around 0x7fff.ffff we're probably not seeing anything above 0x1fff.ffff either)

File: pkg/urbit/noun/serial.c [hunk 1]
```diff
@@ -856,3 +856,111 @@ u3s_cue_atom(u3_atom a)
...
+
+        len_w -= 4;
+      }
+
+      return u3i_mp(a_mp);
+    }
+  }
+
+fail:
+  return u3_none;
```
Comment (ohAitch) [inline pkg/urbit/noun/serial.c:940]: While the reference to the Apple SSL parsing bug is clever, given this is just a return I would favor inlining the gotos unless that would have significant performance implications.

Comment (joemfb) [reply pkg/urbit/noun/serial.c]: Good point.

**Comment by joemfb** [comment]
I don't think there's much to be gained in clarity or simplicity with special-casing as you suggest. But avoiding indirect atom allocation where possible is a win.

hoon:

```
> :time (do 10.000 '123.456.789' |=(a=@t (rush a dem:ag)))
>=
[%took ~s1..5402]
```

old jet:

```
> :time (do 10.000 '123.456.789' |=(a=@t (slaw %ud a)))
[%took ~s0..15c9]
> :time (do 1.000.000 '123.456.789' |=(a=@t (slaw %ud a)))
[%took ~s1..4747]
```

new jet:

```
> :time (do 1.000.000 '123.456.789' |=(a=@t (slaw %ud a)))
[%took ~s0..ecf0]
> :time (do 10.000.000 '123.456.789' |=(a=@t (slaw %ud a)))
[%took ~s8..47b8]
```

(Yes, I had stacked the deck by comparing really big atoms ...)

**Review by Fang- — APPROVED** [review]
Very nice!

File: pkg/urbit/noun/imprison.c [hunk 2]
```diff
@@ -313,12 +313,17 @@ u3i_word(c3_w dat_w)
 u3_atom
 u3i_chub(c3_d dat_d)
 {
-  c3_w dat_w[2] = {
-    dat_d & 0xffffffffULL,
-    dat_d >> 32
-  };
+  if ( c3y == u3a_is_cat(dat_d) ) {
```
Comment (ohAitch) [inline pkg/urbit/noun/imprison.c:316]: Nice. This works on doubles bc it's testing *any* set bit above 31 right?

File: pkg/urbit/tests/jet_tests.c [hunk 3]
```diff
@@ -9,6 +9,108 @@ _setup(void)
...
+      fprintf(stderr, "sift_ud: (bex 32) wrong\r\n");
+      ret_i = 0;
+    }
+
+    u3z(out); u3z(pro);
+  }
+
+
+  {
+    c3_c* num_c = "340.282.366.920.938.463.463.374.607.431.768.211.456";
```
Comment (ohAitch) [inline pkg/urbit/tests/jet_tests.c:93]: And tests including for the indirect handling, A+

File: pkg/urbit/noun/serial.c [hunk 4]
```diff
@@ -856,3 +856,124 @@ u3s_cue_atom(u3_atom a)
...
+      val_d += *byt_y++ - '0';
+
+      len_w -= 4;
+    }
+
+    return u3i_chub(val_d);
+  }
+
+  {
+    //  XX estimate size, allocate once
```
Comment (ohAitch) [inline pkg/urbit/noun/serial.c:928]: Every 4 bytes of input is a couple percent under 10 bits of output right?

**Review by ohAitch — APPROVED** [review]
We're down iirc 1/3 of the lines, the gotos have been turned into a normal if/else, the while len *p++ business is suspicious but I can follow it. Given we're not getting tapes below 24 bytes per character any time soon(which I expect is what hamstrings the hoon on large input), I grudgingly formally concede that this being in is better than not 👍

File: pkg/urbit/noun/serial.c (hunk 4 above)
Comment (ohAitch) [reply pkg/urbit/noun/serial.c:928]: (More inaccurately, as noted above 24 characters is a double / 12 characters is a word, being 10% over isn't a huge deal given u3i_mp will reallocate to exact size anyway)

File: pkg/urbit/noun/imprison.c (hunk 2 above)
Comment (joemfb) [reply pkg/urbit/noun/imprison.c:316]: That's right:

```
#     define u3a_is_cat(som)    (((som) >> 31) ? c3n : c3y)
```

File: pkg/urbit/noun/serial.c (hunk 4 above)
Comment (joemfb) [reply pkg/urbit/noun/serial.c]: Yeah, this worth doing (was previously `~s3`+):

```
> :time (do 100.000 (rap 3 ['123.456.789' (reap 200 '.123.456.789')]) |=(a=@t (slaw %ud a)))
[%took ~s2..dde3]
```
