### PR TITLE
fix (my own) use-after-free in unix dir/file watch

### LINKED ISSUE #1096: bail: oops -- "not a directory"
I tried to copy a generator from a folder outside of my pier and into my pier. The ship crashed with a `bail: oops` and printed the lines below:

```
not a directory: 1/home/gen/gmail
~nec:dojo> 
bail: oops
bailing out
Assertion failed: (0), function u3m_bail, file ../noun/manage.c, line 654.
                                                                          Abort trap: 6 (core dumped)
```

Starting the ship again produces the following:

```
not a directory: 1/home/ren/x-collections-snip

bail: oops
bailing out
Assertion failed: (0), function u3m_bail, file ../noun/manage.c, line 654.
                                                                          Abort trap: 6 (core dumped)
```

I am using `release-candidate`.

### PR DESCRIPTION
**Pull request by joemfb**
In #1092, I was a little too aggressive in fixing a memory-leak in unix.c and introduced a use-after-free.  I thought I had specifically tested that this was not the case. Mea maxima culpa.

(My fix is to copy paths that are hung onto, hopefully making the allocations easier to track.)

closes #1096

/cc @rmariani

### CODE REVIEW

File: vere/unix.c [hunk 1]
```diff
@@ -590,7 +590,8 @@ _unix_watch_file(u3_ufil* fil_u, u3_udir* par_u, c3_c* pax_c)
 
   fil_u->dir = c3n;
   fil_u->dry = c3n;
-  fil_u->pax_c = pax_c;
+  fil_u->pax_c = c3_malloc(1 + strlen(pax_c));
+  strcpy(fil_u->pax_c, pax_c);
```
Comment (belisarius222) [inline vere/unix.c]: If I understand `strcopy()` correctly, this will work properly as long as the input `pax_c` is null-terminated. Are we sure that's always the case? Otherwise the last bit will just be whatever `malloc()` produces.

Comment (joemfb) [reply vere/unix.c]: `pax_c` always comes from `_unix_down()`, which explicitly terminates it.

**Comment by joemfb** [comment]
I just pushed one more change to make this consistent. I don't know why I've struggled so badly with the control flow of this file, but I apologize for it!

**Comment by belisarius222** [comment]
You're struggling because the control flow in `_unix_scan_mount_point()` is too deeply nested to reason about easily. I recommend breaking pieces of it out into functions so the memory management gets more localized along with the rest of the reasoning. The branch that calls `_unix_down()` should probably be its own routine, and we don't need so many `continue` statements.

**Comment by joemfb** [comment]
I agree, and I'm happy to do so. But I'd like to go ahead and merge this first -- it's a tested fix for a major active bug. It'll take me a little bit to clean those functions up.
