### PR TITLE
vere: filter out content-length header from eyre

### LINKED ISSUE #2003: Multiple Content-Length Headers being returned from vere
Howdy, all. When trying to query my fake zod's landscape login endpoint, I was getting some parsing errors in node/postman. After further investigation, it turns out vere is returning 2 content-length headers, which causes a lot of clients to fail.

When running:
`curl http://localhost:8080/~/login -X POST -H "Content-Type: application/json" -d '{"password": "lidlut-tabwed-pillex-ridrup"}' -D -`

The output is:
```
HTTP/1.1 200 ok
Date: Fri, 29 Nov 2019 17:23:18 GMT
Connection: keep-alive
Content-Length: 1817
Server: urbit/vere-0.9.2
content-length: 1817
content-type: text/html
```

### PR DESCRIPTION
**Pull request by pkova**
Fixes #2003.

`curl -I -X GET http://localhost:80/~/login`
```
HTTP/1.1 200 ok
Date: Wed, 04 Dec 2019 15:13:56 GMT
Connection: keep-alive
Content-Length: 1817
Server: urbit/vere-0.10.0
content-type: text/html
```
`curl -I -X GET http://localhost:80/~/i-dont-exist`
```
HTTP/1.1 307 moved
Date: Wed, 04 Dec 2019 15:26:36 GMT
Connection: close
Server: urbit/vere-0.10.0
location: /~/login?redirect=/~/i-dont-exist
```

### CODE REVIEW

File: pkg/urbit/vere/http.c [hunk 1]
```diff
@@ -518,9 +518,11 @@ _http_start_respond(u3_hreq* req_u,
...
-                          hed_u->nam_c, hed_u->nam_w, 0, 0,
-                          hed_u->val_c, hed_u->val_w);
+    if ( 0 != strncmp(hed_u->nam_c, "content-length", 14) ) {
+      h2o_add_header_by_str(&rec_u->pool, &rec_u->res.headers,
+                            hed_u->nam_c, hed_u->nam_w, 0, 0,
+                            hed_u->val_c, hed_u->val_w);
+    }
 
     if ( 0 == strncmp(hed_u->nam_c, "content-length", 14) ) {
       has_len_i = 1;
```
Comment (joemfb) [inline pkg/urbit/vere/http.c]: Let's combine these two conditionals into an if/else block.

Comment (pkova) [reply pkg/urbit/vere/http.c]: Done!
