### PR TITLE
publish: don't insert newline

### LINKED ISSUE #3596: publish: editor inserts newline at beginning of document
It seems to be only upon editing, and the newline does not appear upon merely viewing, but to reproduce:

1) Create a document in publish.
2) Save
3) Edit document
4) Note newline at beginning of editor.

### PR DESCRIPTION
**Pull request by tylershuster**
Fixes #3596

Not sure if this needs to be done in `<Note />` as well, just assumed that it does because it draws from the same thing.

### CODE REVIEW

File: pkg/interface/src/views/apps/publish/components/Note.tsx [hunk 1]
```diff
@@ -45,7 +45,7 @@ export function Note(props: NoteProps & RouteComponentProps) {
 
   const comments = note?.comments || [];
   const file = note?.file;
-  const newfile = file ? file.slice(file.indexOf(";>") + 2) : "";
+  const newfile = file ? file.slice(file.indexOf(";>") + 3) : "";
```
Comment (matildepark) [inline pkg/interface/src/views/apps/publish/components/Note.tsx:48]: Imagine a world where the fix in EditPost is applied and people start using it in their posts, no longer having the newline at the start. Won't this then cut off the first character, if we do this in both places?

Comment (tylershuster) [reply pkg/interface/src/views/apps/publish/components/Note.tsx]: Good point

**Review by matildepark — APPROVED** [review]
